[package]
name = "wise_key"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { features = [
    "default",
    "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }

# For image support:
egui_extras = { features = ["default", "image"] }

#inputs simulation
enigo = "0.2.1"

#inputs record
device_query = "2.1.0"
