[package]
name = "wise_key"
version = "0.1.0"
edition = "2021"

[dependencies]
#inputs simulation
enigo = "*"

#inputs record
rdev = { path = "src/rdev", features = ["unstable_grab"] }

#global
lazy_static = "*"

#embed code
rhai = { version = "*", features = ["internals", "only_i32"] }

#clipboard
arboard = "*"

crossbeam-channel = "*"
